version: '3'
services:
  web:
    build:
      context: ./web
    ports:
      - "8082:8080" # Map host port 8080 to container port 3000 for web
    networks:
      - app-network
    depends_on:
      - api
  api:
    build:
      context: ./api
    ports:
      - "3001:3000" # Map host port 3001 to container port 3000 for API
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
